return {
    "nvim-lua/plenary.nvim",
    "nvim-tree/nvim-web-devicons",
    "hrsh7th/nvim-cmp",
    "hrsh7th/cmp-nvim-lsp",
    "hrsh7th/cmp-path",
    "hrsh7th/cmp-buffer",
    "nvim-telescope/telescope.nvim",
    "nvim-treesitter/nvim-treesitter",
    "nvim-mini/mini.pairs",
    { "ThePrimeagen/harpoon", branch = "harpoon2" },
    "folke/tokyonight.nvim",
    "nvim-lualine/lualine.nvim",
    "brenoprata10/nvim-highlight-colors",
    "tpope/vim-fugitive",
    "mbbill/undotree",
    "ojroques/vim-oscyank",
    "stevearc/oil.nvim",
    "mohm-hyd/Vimdoc"
}
